version: "3.8"

services:

  nginx-test-application:
    build: app
    container_name: nginx-test-application
    restart: unless-stopped
#    volumes:
#    env_file:
    ports:
      - "8000:8000"
    command: /bin/sh -c "infra/runserver.sh"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "NginxTest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/Library/PostgreSQL/16/data/
volumes:
  postgres_data:
