# Generated by Django 5.1 on 2024-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('remote_ip', models.GenericIPAddressField()),
                ('remote_user', models.CharField(max_length=100)),
                ('request_method', models.CharField(max_length=100)),
                ('request_path', models.CharField(max_length=100)),
                ('request_protocol', models.CharField(max_length=100)),
                ('response_code', models.IntegerField()),
                ('response_size', models.IntegerField()),
                ('referrer', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=100)),
            ],
        ),
    ]
